name: Run Supabase Ping

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run Ping Script
        run: node --dns-result-order=ipv4first ping-supabase.js
